In [1]:
import os

mingw_path = 'C:\\Users\\a1\\mingw\\mingw64\\bin'

os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']
import xgboost as xgb
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
train = pd.read_csv('new_train_mean_cl.csv')
test = pd.read_csv('new_test_mean_cl.csv')

In [2]:
del test['Unnamed: 0']
del train['Unnamed: 0']

In [3]:
test = test.drop_duplicates(subset='id').set_index(keys='id').sort_index()

In [4]:
test = test[[u'Semana', u'Producto_ID', u'Cliente_ID', u'lag1', u'lag2', u'lag3', u'Agencia_ID', u'Canal_ID', u'Ruta_SAK',
             u'Cliente_ID_town_count', u'price', u'weight', u'pieces', u'cluster_nombre', u'drink', u'w_per_piece', u'OXXO', 
             u'ARTELI', u'ALSUPER', u'BODEGA', u'CALIMAX', u'XICANS', u'ABARROTES', u'CARNICERIA', u'FRUTERIA', 
             u'DISTRIBUIDORA', u'ELEVEN', u'HOTEL', u'HOSPITAL', u'CAFE', u'FARMACIA', u'CREME', u'SUPER', u'COMOD', 
             u'MODELOR', u'UNKN']]

In [5]:
def RMSLE_score(pred, true):
    score = np.power(pred-true, 2)
    return np.sqrt(np.mean(score))

In [6]:
from sklearn import cross_validation
from sklearn.preprocessing import LabelEncoder
from xgboost.sklearn import XGBRegressor
from sklearn import grid_search

In [7]:
X = train
y = train['Demanda_uni_equil_log0'].copy()
del train['Demanda_uni_equil_log0']

In [8]:
del X['drink']
del X['DISTRIBUIDORA']
del X['ARTELI']
del X['CALIMAX']
del X['MODELOR']
del X['HOSPITAL']
del X['HOTEL']
del test['drink']
del test['DISTRIBUIDORA']
del test['ARTELI']
del test['CALIMAX']
del test['MODELOR']
del test['HOSPITAL']
del test['HOTEL']

In [23]:
mean_submission = pd.read_csv('submit_mean.csv').set_index(keys='id').sort_index()
for w in [6, 7]: 
    train_index = (train['Semana'] == w)
    test_index = ~(train['Semana'] == w)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    xgbr = XGBRegressor(colsample_bytree=0.8,learning_rate=0.05, max_depth=15, n_estimators=100, reg_lambda=0.01, subsample=0.8)
    xgbr.fit(X_train, y_train)
    preds = xgbr.predict(X_test)
    preds[preds<0] = 0
    print RMSLE_score(preds, y_test)
    subms = xgbr.predict(test)
    mean_submission['xgb_demanda'+str(w)] = np.expm1(subms)
mean_submission.to_csv('subm_xgb_mean6.csv')

0.484640830711
0.47437522819

In [41]:
subms = xgbr.predict(test)

In [121]:
pd.Series(np.expm1(subms)).to_csv('subm_xgb.csv')

In [12]:
mean_submission = pd.read_csv('submit_mean.csv').set_index(keys='id').sort_index()

In [42]:
mean_submission['xgb_demanda'] = np.expm1(subms)

In [20]:
mean_submission['subm'] = 0.3*mean_submission['xgb_demanda6']+0.7*(0.3*mean_submission['xgb_demanda6']+0.3*mean_submission['xgb_demanda7']+
                                                                   0.2*mean_submission['xgb_demanda8']+0.2*mean_submission['xgb_demanda9'])

In [22]:
mean_submission['subm'].to_csv('subm_xgb.csv')

In [24]:
mean_submission

         Demanda_uni_equil  xgb_demanda6  xgb_demanda7
id
0                  3.77390      3.426123      5.721072
1                  1.46508      1.458099      1.418618
2                  2.08898      2.076922      2.007024
3                  1.57699      1.437317      1.396789
4                  3.18219      2.780858      3.154006
5                  3.18412      2.787885      2.657208
6                  1.29527      1.632302      1.403468
7                  4.39736      4.314917      5.478069
8                  4.83532      2.719286      2.701025
9                  5.12847      2.518623      2.513879
10                 8.62258     10.827685     10.956614
11                 2.32947      1.965260      2.002116
12                 3.38700      1.744697      2.044625
13                 7.46928      3.945465      3.635644
14                 2.20283      2.663009      2.823104
15                 3.58978      3.660593      3.923105
16                 1.41734      1.398794      1.550973
17                 2.25311      1.501373      1.517335
18                 1.57593      1.034407      1.494061
19                 3.55694      2.763276      2.839965
20                 4.93404      4.091632      4.028941
21                 9.50158      4.972658     10.441873
22                10.20601      8.259273      8.346764
23                 1.66180      1.394537      1.439486
24                 1.28309      1.527367      1.490270
25                 6.76671      5.719775      5.917659
26                 2.07738      1.846033      1.531873
27                 3.98544      3.287784      4.582747
28                 1.64120      1.689235      1.845715
29                 1.38381      1.954746      1.930927
...                    ...           ...           ...
6999221            2.37418      1.316582      1.443370
6999222            2.42978      1.766854      1.815562
6999223            4.04305      3.615120      4.399407
6999224            1.50756      1.576537      1.558327
6999225           10.60848     11.433860     10.964457
6999226            3.52533      3.899218      5.034446
6999227            5.39426      6.360854      7.356496
6999228            1.97878      1.764550      2.482959
6999229            3.04111      3.955751      3.883440
6999230           53.29509     42.114189     46.508869
6999231            1.90925      1.425020      1.377616
6999232            2.81722      2.367710      2.434778
6999233            1.39598      1.355418      1.480364
6999234            4.57274      1.284417      1.041037
6999235            5.37828      3.588211      4.056904
6999236            1.47293      1.396803      1.442935
6999237            2.44243      2.271025      2.360015
6999238            5.33667      4.184835      4.461240
6999239            5.65737      5.220759      5.457982
6999240            1.08816      1.041999      0.964488
6999241            1.13249      1.420616      1.499816
6999242            1.55666      1.408768      1.451602
6999243            7.17569      5.552170      5.790404
6999244           36.70040     46.046253     48.517250
6999245            8.08152      6.890777      7.220655
6999246            2.32163      1.554768      1.505223
6999247            2.28680      2.513649      2.480212
6999248            2.92867      2.777719      2.897672
6999249            2.55866      2.973928      3.259991
6999250            0.69695      1.289126      1.274598

[6999251 rows x 3 columns]

In [20]:
test.head()

,Semana,Producto_ID,Cliente_ID,lag1,lag2,lag3,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID_town_count,...,ABARROTES,CARNICERIA,FRUTERIA,ELEVEN,CAFE,FARMACIA,CREME,SUPER,COMOD,UNKN
id,,,,,,,,,,,,,,,,,,,,,
0,11,35305,4639078,0.000000,1.609438,0.0,4037,1,2209,543723,...,0,0,0,0,0,0,0,0,0,1
1,11,1238,4705135,0.000000,0.000000,0.0,2237,1,1226,553984,...,0,0,0,0,0,0,0,0,0,1
2,10,32940,4549769,1.098612,1.098612,0.0,2045,1,2831,249200,...,0,0,0,0,0,0,0,0,0,1
3,11,43066,4717855,0.000000,0.000000,0.0,1227,1,4448,507639,...,0,0,0,0,0,0,0,0,0,1
4,11,1277,966351,0.000000,0.000000,0.0,1219,1,1130,572966,...,0,0,0,0,0,0,0,0,0,1